# Spring
spring.output.ansi.enabled: ALWAYS
spring.profiles.active: local
spring.application.name: generator-sample
spring.application.root-package: com.codeartist.component.generator.sample
spring.config.import: classpath:default.yaml
# Spring Cloud Consul
spring.cloud.consul.enabled: false
# Spring Datasource
spring.datasource.url: jdbc:h2:mem:default;MODE=MySQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:sql/init.sql'
spring.datasource.hikari.minimum-idle: 1
spring.datasource.hikari.maximum-pool-size: 2
spring.datasource.hikari.max-lifetime: 1200000
spring.datasource.hikari.connection-test-query: SELECT 1
