# Spring
spring.output.ansi.enabled: ALWAYS
spring.profiles.active: local
spring.application.name: cache-sample
spring.application.root-package: com.codeartist.component.cache.sample
spring.config.import: classpath:default.yaml
# Spring Redis
spring.redis.host: localhost
spring.redis.timeout: 10s
spring.redis.lettuce.shutdown-timeout: 1000ms
spring.redis.lettuce.pool.max-active: 10
spring.redis.lettuce.pool.max-idle: 8
spring.redis.lettuce.pool.max-wait: -1ms
spring.redis.lettuce.pool.min-idle: 0
# Spring Redis
spring.redis.multi.pms.host: localhost
spring.redis.multi.pms.timeout: 10s
spring.redis.multi.pms.lettuce.shutdown-timeout: 1000ms
spring.redis.multi.pms.lettuce.pool.max-active: 10
spring.redis.multi.pms.lettuce.pool.max-idle: 8
spring.redis.multi.pms.lettuce.pool.max-wait: -1ms
spring.redis.multi.pms.lettuce.pool.min-idle: 0
