# Spring
spring.output.ansi.enabled: ALWAYS
spring.profiles.active: local
spring.application.name: core-sample
spring.root.package: com.codeartist.component.core.sample
spring.config.import: classpath:default.yaml
# Spring Cloud Consul
spring.cloud.consul.enabled: false
